# Generated by Django 4.0.4 on 2022-05-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('EC', 'Electronic devices'), ('SP', 'Sports Equipments'), ('GN', 'General Items'), ('RE', 'Rare or limited Items'), ('ET', 'Books, Music etc')], default='GN', max_length=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
